# Code Whisperers GitHub Action
# Add this to your repository: .github/workflows/code-review.yml
#
# Automatically reviews PRs and commits with AI-powered code review

name: 🎭 Code Whisperers Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better context

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Code Whisperers
        run: |
          pip install git+https://github.com/sethjchalmers/code-whisperers.git

      - name: Run Code Review (PR)
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Review changes in this PR vs base branch
          python -m cli.main review \
            --base ${{ github.event.pull_request.base.sha }} \
            --head ${{ github.event.pull_request.head.sha }} \
            --output review-report.md \
            --format markdown

          # Post summary as PR comment
          echo "## 🎭 Code Whisperers Review" > pr-comment.md
          echo "" >> pr-comment.md
          cat review-report.md >> pr-comment.md

      - name: Run Code Review (Push)
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m cli.main review \
            --diff HEAD~1 \
            --format text

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('pr-comment.md', 'utf8');

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(c =>
              c.user.type === 'Bot' &&
              c.body.includes('🎭 Code Whisperers Review')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }

      - name: Upload Review Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-review-report
          path: review-report.md
          retention-days: 30
